name: Update Content
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PUSH_TOKEN }}
      - name: Get new content
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          npm i
          npm run archive:update
      - name: Commit and push changes
        run: |
          git config --global user.name 'Rafal Pastuszak'
          git config --global user.email 'paprikka@users.noreply.github.com'
          git add .
          git commit -m "chore(content): $(date +'%d-%m-%Y')"
          git push
