name: Update Content
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get new content
        run: |
          npm i
          npm run archive:update
      - name: Commit changes
        run: |
          git config --global user.name 'Rafal Pastuszak'
          git config --global user.email 'paprikka@users.noreply.github.com'
          git commit -am "chore(content): $(date +'%d-%m-%Y')"
          git push
